# Generated by Django 5.2.8 on 2026-01-02 02:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('short_description', models.CharField(blank=True, max_length=200, verbose_name='Short Description')),
                ('pricing_type', models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly Rate'), ('from', 'Starting From'), ('variable', 'Variable'), ('free', 'Free')], default='fixed', max_length=20, verbose_name='Pricing Type')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Price')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Minimum Price')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Maximum Price')),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Internal cost for profit calculation', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cost')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Tax Rate (%)')),
                ('duration_minutes', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Duration (minutes)')),
                ('buffer_before', models.PositiveIntegerField(default=0, help_text='Preparation time before service', verbose_name='Buffer Before (minutes)')),
                ('buffer_after', models.PositiveIntegerField(default=0, help_text='Cleanup time after service', verbose_name='Buffer After (minutes)')),
                ('max_capacity', models.PositiveIntegerField(default=1, help_text='Maximum simultaneous bookings', verbose_name='Maximum Capacity')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icon')),
                ('color', models.CharField(blank=True, max_length=7, verbose_name='Color')),
                ('is_bookable', models.BooleanField(default=True, help_text='Can be booked through appointments', verbose_name='Is Bookable')),
                ('requires_confirmation', models.BooleanField(default=False, help_text='Booking requires staff confirmation', verbose_name='Requires Confirmation')),
                ('allow_online_booking', models.BooleanField(default=True, verbose_name='Allow Online Booking')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured services', verbose_name='Featured')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Barcode')),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='Discount Type')),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Discount Value')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, help_text='If set, overrides calculated price', max_digits=10, null=True, verbose_name='Fixed Price')),
                ('validity_days', models.PositiveIntegerField(blank=True, help_text='Days to use package after purchase', null=True, verbose_name='Validity (days)')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum times package can be used', null=True, verbose_name='Maximum Uses')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/packages/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Featured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Package',
                'verbose_name_plural': 'Service Packages',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServicesConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_duration', models.PositiveIntegerField(default=60, help_text='Default service duration in minutes', verbose_name='Default Duration (minutes)')),
                ('default_buffer_time', models.PositiveIntegerField(default=0, help_text='Default buffer time between services', verbose_name='Buffer Time (minutes)')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Default Tax Rate')),
                ('show_prices', models.BooleanField(default=True, help_text='Display prices in service catalog', verbose_name='Show Prices')),
                ('show_duration', models.BooleanField(default=True, help_text='Display duration in service catalog', verbose_name='Show Duration')),
                ('allow_online_booking', models.BooleanField(default=True, help_text='Allow services to be booked online', verbose_name='Allow Online Booking')),
                ('include_tax_in_price', models.BooleanField(default=True, help_text='Prices include tax', verbose_name='Include Tax in Price')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Currency')),
                ('price_decimal_places', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(4)], verbose_name='Price Decimal Places')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Services Configuration',
                'verbose_name_plural': 'Services Configuration',
            },
        ),
        migrations.CreateModel(
            name='ServiceAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Price')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='Duration (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('services', models.ManyToManyField(blank=True, related_name='addons', to='services.service', verbose_name='Available for Services')),
            ],
            options={
                'verbose_name': 'Service Addon',
                'verbose_name_plural': 'Service Addons',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text="Icon name (e.g., 'cut-outline')", max_length=50, verbose_name='Icon')),
                ('color', models.CharField(blank=True, help_text="Hex color code (e.g., '#3880ff')", max_length=7, verbose_name='Color')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/categories/', verbose_name='Image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='services.servicecategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Service Category',
                'verbose_name_plural': 'Service Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='ServicePackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.servicepackage')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='services.service')),
            ],
            options={
                'verbose_name': 'Package Item',
                'verbose_name_plural': 'Package Items',
                'ordering': ['order'],
                'unique_together': {('package', 'service')},
            },
        ),
        migrations.AddField(
            model_name='servicepackage',
            name='services',
            field=models.ManyToManyField(related_name='packages', through='services.ServicePackageItem', to='services.service', verbose_name='Services'),
        ),
        migrations.CreateModel(
            name='ServiceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Added to base service price', max_digits=10, verbose_name='Price Adjustment')),
                ('duration_adjustment', models.IntegerField(default=0, help_text='Added to base service duration', verbose_name='Duration Adjustment (minutes)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='services.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Service Variant',
                'verbose_name_plural': 'Service Variants',
                'ordering': ['order', 'name'],
                'unique_together': {('service', 'name')},
            },
        ),
    ]
