# Generated by Django 6.0.1 on 2026-02-27 22:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='allow_online_booking',
            field=models.BooleanField(default=True, verbose_name='Allow Online Booking'),
        ),
        migrations.AlterField(
            model_name='service',
            name='barcode',
            field=models.CharField(blank=True, max_length=50, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='service',
            name='buffer_after',
            field=models.PositiveIntegerField(default=0, help_text='Cleanup time', verbose_name='Buffer After'),
        ),
        migrations.AlterField(
            model_name='service',
            name='buffer_before',
            field=models.PositiveIntegerField(default=0, help_text='Preparation time', verbose_name='Buffer Before'),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='service',
            name='color',
            field=models.CharField(blank=True, max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Internal cost', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cost'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5)], verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_bookable',
            field=models.BooleanField(default=True, help_text='Can be booked through appointments', verbose_name='Is Bookable'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is Featured'),
        ),
        migrations.AlterField(
            model_name='service',
            name='max_capacity',
            field=models.PositiveIntegerField(default=1, help_text='Max simultaneous bookings', verbose_name='Max Capacity'),
        ),
        migrations.AlterField(
            model_name='service',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Maximum Price'),
        ),
        migrations.AlterField(
            model_name='service',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Minimum Price'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='service',
            name='pricing_type',
            field=models.CharField(choices=[('fixed', 'Fixed Price'), ('hourly', 'Hourly Rate'), ('from', 'Starting From'), ('variable', 'Variable'), ('free', 'Free')], default='fixed', max_length=20, verbose_name='Pricing Type'),
        ),
        migrations.AlterField(
            model_name='service',
            name='requires_confirmation',
            field=models.BooleanField(default=False, verbose_name='Requires Confirmation'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='sku',
            field=models.CharField(blank=True, max_length=50, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='service',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='service',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Tax Rate'),
        ),
        migrations.AlterField(
            model_name='serviceaddon',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='serviceaddon',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Duration (minutes)'),
        ),
        migrations.AlterField(
            model_name='serviceaddon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='serviceaddon',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='serviceaddon',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='serviceaddon',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='addons', to='services.service', verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='color',
            field=models.CharField(blank=True, help_text='Hex color', max_length=7, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='icon',
            field=models.CharField(blank=True, help_text='Icon name', max_length=50, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/categories/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='services.servicecategory', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20, verbose_name='Discount Type'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Discount Value'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='fixed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides calculated price', max_digits=10, null=True, verbose_name='Fixed Price'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/packages/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Is Featured'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Uses'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='services',
            field=models.ManyToManyField(related_name='packages', through='services.ServicePackageItem', to='services.service', verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='slug',
            field=models.SlugField(max_length=200, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='servicepackage',
            name='validity_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days to use after purchase', null=True, verbose_name='Validity Days'),
        ),
        migrations.AlterField(
            model_name='servicepackageitem',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='services.servicepackage', verbose_name='Package'),
        ),
        migrations.AlterField(
            model_name='servicepackageitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='servicepackageitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_items', to='services.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='servicepackageitem',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sort Order'),
        ),
        migrations.AlterField(
            model_name='servicessettings',
            name='allow_online_booking',
            field=models.BooleanField(default=True, verbose_name='Allow Online Booking'),
        ),
        migrations.AlterField(
            model_name='servicessettings',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='servicessettings',
            name='default_buffer_time',
            field=models.PositiveIntegerField(default=0, help_text='Default buffer time between services', verbose_name='Default Buffer Time'),
        ),
        migrations.AlterField(
            model_name='servicessettings',
            name='default_duration',
            field=models.PositiveIntegerField(default=60, help_text='Default service duration in minutes', verbose_name='Default Duration'),
        ),
        migrations.AlterField(
            model_name='servicessettings',
            name='default_tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Default Tax Rate'),
        ),
        migrations.AlterField(
            model_name='servicessettings',
            name='include_tax_in_price',
            field=models.BooleanField(default=True, help_text='Prices include tax', verbose_name='Include Tax in Price'),
        ),
        migrations.AlterField(
            model_name='servicessettings',
            name='show_duration',
            field=models.BooleanField(default=True, help_text='Display duration in catalog', verbose_name='Show Duration'),
        ),
        migrations.AlterField(
            model_name='servicessettings',
            name='show_prices',
            field=models.BooleanField(default=True, help_text='Display prices in catalog', verbose_name='Show Prices'),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='duration_adjustment',
            field=models.IntegerField(default=0, help_text='Added to base duration (min)', verbose_name='Duration Adjustment'),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='price_adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Added to base price', max_digits=10, verbose_name='Price Adjustment'),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='services.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Sort Order'),
        ),
    ]
